export const DATA_SOURCE = 'DATA_SOURCE';
export const DISTRIBUTOR_REPOSITORY = 'DISTRIBUTOR_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_ORDER_REPOSITORY = 'PRODUCT_ORDER_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const PRICE_REPOSITORY = 'PRICE_REPOSITORY';
export const DISTRIBUTOR_RELATION_REPOSITORY =
  'DISTRIBUTOR_RELATION_REPOSITORY';
export const PRODUCT_ORDER_DETAIL_REPOSITORY =
  'PRODUCT_ORDER_DETAIL_REPOSITORY';
export const INVENTORY_REPOSITORY = 'INVENTORY_REPOSITORY';
export const PRODUCT_LINK_REPOSITORY = 'PRODUCT_LINK_REPOSITORY';
export const PRODUCT_VARIANT_REPOSITORY = 'PRODUCT_VARIANT_REPOSITORY';
export const CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY';
export const PAYMENT_METHOD_REPOSITORY = 'PAYMENT_METHOD_REPOSITORY';
export const CITY_REPOSITORY = 'CITY_REPOSITORY';
export const CUSTOMER_ORDER_REPOSITORY = 'CUSTOMER_ORDER_REPOSITORY';
export const CUSTOMER_ORDER_DETAIL_REPOSITORY =
  'CUSTOMER_ORDER_DETAIL_REPOSITORY';

export const jwtConstants = { secret: 'jasonwebtoken' };
