export const DATA_SOURCE = 'DATA_SOURCE';
export const DISTRIBUTOR_REPOSITORY = 'DISTRIBUTOR_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_ORDER_REPOSITORY = 'PRODUCT_ORDER_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const PRICE_REPOSITORY = 'PRICE_REPOSITORY';
export const DISTRIBUTOR_RELATION_REPOSITORY =
  'DISTRIBUTOR_RELATION_REPOSITORY';
export const PRODUCT_ORDER_DETAIL_REPOSITORY =
  'PRODUCT_ORDER_DETAIL_REPOSITORY';
DISTRIBUTOR_RELATION_REPOSITORY;
